Class NovoLib.CodeGen.Builder Extends %RegisteredObject
{

// Create Classes

// Create DB Classes

// Create REST DispathHandler

// Create CSP pages

// Create HTML pages

// Create Angular Components

// Create persistant tables

// Use JSON file

ClassMethod Generate(pTemplate As %String) As %Status
{
	//Create folder
	
	// Create support Class/Include files
	
	
	
	write "Hellow Don"
	Quit $$$OK
}

}
